version: '3.4'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  javaapp:
    image: javapp
    environment:
      - VIRTUAL_HOST=m

  javaapp1:
    image: javapp
    environment:
      - VIRTUAL_HOST=m

  javaapp2:
    image: javapp
    environment:
      - VIRTUAL_HOST=m

  javaapp3:
    image: javapp
    environment:
      - VIRTUAL_HOST=m

